version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    volumes:
      - ./client/dist:/app/dist

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - PORT=4001
      - API_URL=https://api.example.com
    volumes:
      - ./client/dist:/app/client/dist
    depends_on:
      - client
