version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - PORT=4001
      - API_URL=https://production-api.example.com
      - ASSET_PATH=/app/client/dist/.vite
    volumes:
      # Only mount the client build output needed by the server
      - ./client/dist:/app/client/dist
    depends_on:
      - client
